# Generated by Django 5.1.7 on 2026-07-03 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="name",
        ),
    ]
