# Generated by Django 6.0.6 on 2026-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_apikey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="URL to POST shipment status change events to.",
                max_length=500,
                null=True,
            ),
        ),
    ]
