# Generated by Django 6.0.6 on 2026-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_apikey_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ydm', 'YDM'), ('vendor', 'Vendor')], db_index=True, default='vendor', max_length=20),
        ),
    ]
