# Generated by Django 6.0.6 on 2026-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ydm', 'YDM'), ('vendor', 'Vendor'), ('YDM_Rider', 'YDM Rider')], db_index=True, default='vendor', max_length=20),
        ),
    ]
