# Generated by Django 6.0.6 on 2026-07-13 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "external_order_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("sender_address", models.TextField(blank=True, null=True)),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(db_index=True, max_length=50)),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("recipient_address", models.TextField()),
                (
                    "recipient_city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "recipient_district",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "cod_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("PREPAID", "Prepaid"), ("COD", "Cash on Delivery")],
                        db_index=True,
                        default="COD",
                        max_length=20,
                    ),
                ),
                ("product", models.JSONField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                ("pickup_date", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_VERIFIED", "Order Verified"),
                            ("RECEIVED_AT_OFFICE", "Received At Office"),
                            ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                            ("ORDER_DISPATCHED", "Order Dispatched"),
                            ("OUT_FOR_DELIVERY", "Out For Delivery"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNING_TO_VENDOR", "Returning to Vendor"),
                            ("RETURNED_TO_VENDOR", "Returned to Vendor"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        db_index=True,
                        default="ORDER_PLACED",
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("FAILURE", "Failure Reason"),
                            ("CANCELLATION", "Cancellation Reason"),
                            ("HOLD", "Hold Reason"),
                            ("RESCHEDULE", "Reschedule Reason"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="logistics.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_VERIFIED", "Order Verified"),
                            ("RECEIVED_AT_OFFICE", "Received At Office"),
                            ("READY_FOR_DISPATCH", "Ready for Dispatch"),
                            ("ORDER_DISPATCHED", "Order Dispatched"),
                            ("OUT_FOR_DELIVERY", "Out For Delivery"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNING_TO_VENDOR", "Returning to Vendor"),
                            ("RETURNED_TO_VENDOR", "Returned to Vendor"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="logistics.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="logistics_o_user_id_95b14b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="logistics_o_user_id_2fe2af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "payment_type"], name="logistics_o_status_202864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["assigned_rider", "status"],
                name="logistics_o_assigne_364b70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["recipient_city", "status"],
                name="logistics_o_recipie_ac92c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["order", "comment_type"], name="logistics_o_order_i_045d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["order", "created_at"], name="logistics_o_order_i_a49d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "created_at"], name="logistics_o_order_i_835a01_idx"
            ),
        ),
    ]
