# Generated by Django 6.0.6 on 2026-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_ydmlogisticssetting_order_delivery_location_type_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderstatushistory",
            name="logistics_o_order_i_835a01_idx",
        ),
        migrations.DeleteModel(
            name="OrderStatusHistory",
        ),
    ]
