# Generated by Django 6.0.6 on 2026-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_orderstatushistory_logistics_o_order_i_835a01_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchangelog',
            name='old_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
