# Generated by Django 6.0.6 on 2026-07-15 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_orderchangelog_old_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordercomment',
            name='logistics_o_order_i_045d98_idx',
        ),
        migrations.AddIndex(
            model_name='ordercomment',
            index=models.Index(fields=['order'], name='logistics_o_order_i_e69abc_idx'),
        ),
        migrations.RemoveField(
            model_name='ordercomment',
            name='comment_type',
        ),
    ]
