# Generated by Django 6.0.6 on 2026-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_ordercomment_logistics_o_order_i_045d98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
