# Generated by Django 6.0.6 on 2026-07-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
