# Generated by Django 6.0.6 on 2026-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('rider_assigned', 'Rider Assigned'), ('status_updated', 'Status Updated')], db_index=True, max_length=50),
        ),
    ]
