# Generated by Django 6.0.6 on 2026-07-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridercommissionrate',
            options={'ordering': ['order_min_count']},
        ),
        migrations.RenameField(
            model_name='ridercommissionrate',
            old_name='order_max_amount',
            new_name='order_max_count',
        ),
        migrations.RenameField(
            model_name='ridercommissionrate',
            old_name='order_min_amount',
            new_name='order_min_count',
        ),
    ]
